version: '3'
services:
  web:
    build: .
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html
    links:
      - db
    env_file:
      - .env
      - .env.dev
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - "${DATABASE_PATH}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 9020:80
    volumes:
      - /sessions
    links:
      - db