<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.D2ZDN6M' shared service.

return $this->privates['.service_locator.D2ZDN6M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'evento' => ['privates', '.errored..service_locator.D2ZDN6M.App\\Entity\\Evento', NULL, 'Cannot autowire service ".service_locator.D2ZDN6M": it references class "App\\Entity\\Evento" but no such service exists.'],
]);
