<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.O_TlQTA' shared service.

return $this->privates['.service_locator.O_TlQTA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pagSeguroService' => ['privates', 'App\\Payment\\PagSeguro\\PagSeguroService', 'getPagSeguroServiceService.php', true],
]);
