<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Payment\PagSeguro\PagSeguroService' shared autowired service.

include_once $this->targetDirs[3].'/src/Payment/PagSeguro/PagSeguroService.php';

return $this->privates['App\Payment\PagSeguro\PagSeguroService'] = new \App\Payment\PagSeguro\PagSeguroService($this->getEnv('PAGSEGURO_ENV'), $this->getEnv('PAGSEGURO_EMAIL'), $this->getEnv('PAGSEGURO_TOKEN'));
