<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.JBB4Uey.App\Entity\UsuarioEvento' shared service.

include_once $this->targetDirs[3].'/src/Entity/UsuarioEvento.php';

return $this->privates['.errored..service_locator.JBB4Uey.App\Entity\UsuarioEvento'] = new \App\Entity\UsuarioEvento();
