<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH0aXrs6\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH0aXrs6/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerH0aXrs6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerH0aXrs6\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerH0aXrs6\srcApp_KernelProdContainer([
    'container.build_hash' => 'H0aXrs6',
    'container.build_id' => '1d081ce5',
    'container.build_time' => 1565640391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH0aXrs6');
