<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HmaUIT1' shared service.

return $this->privates['.service_locator.HmaUIT1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'evento' => ['privates', '.errored..service_locator.HmaUIT1.App\\Entity\\Evento', NULL, 'Cannot autowire service ".service_locator.HmaUIT1": it references class "App\\Entity\\Evento" but no such service exists.'],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'pagSeguroService' => ['privates', 'App\\Payment\\PagSeguro\\PagSeguroService', 'getPagSeguroServiceService.php', true],
]);
