<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.owo64J_' shared service.

return $this->privates['.service_locator.owo64J_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'seguroService' => ['privates', 'App\\Payment\\PagSeguro\\PagSeguroService', 'getPagSeguroServiceService.php', true],
    'usuarioEventoRepository' => ['privates', 'App\\Repository\\UsuarioEventoRepository', 'getUsuarioEventoRepositoryService.php', true],
]);
