<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Rn8tr7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Rn8tr7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Rn8tr7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Rn8tr7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4Rn8tr7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4Rn8tr7',
    'container.build_id' => '0e1c3311',
    'container.build_time' => 1563567647,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Rn8tr7');
