<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioEvento extends \App\Entity\UsuarioEvento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'dataPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'statusPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'codePagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'objetoPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'evento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'cliente'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'dataPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'statusPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'codePagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'objetoPagamento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'evento', '' . "\0" . 'App\\Entity\\UsuarioEvento' . "\0" . 'cliente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioEvento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPagamento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPagamento', []);

        return parent::getDataPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPagamento(\DateTimeInterface $dataPagamento): \App\Entity\UsuarioEvento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPagamento', [$dataPagamento]);

        return parent::setDataPagamento($dataPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvento(): ?\App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvento', []);

        return parent::getEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvento(?\App\Entity\Evento $evento): \App\Entity\UsuarioEvento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvento', [$evento]);

        return parent::setEvento($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente(): ?\App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(?\App\Entity\Cliente $cliente): \App\Entity\UsuarioEvento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusPagamento', []);

        return parent::getStatusPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusPagamento($statusPagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusPagamento', [$statusPagamento]);

        return parent::setStatusPagamento($statusPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePagamento', []);

        return parent::getCodePagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePagamento($codePagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePagamento', [$codePagamento]);

        return parent::setCodePagamento($codePagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetoPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetoPagamento', []);

        return parent::getObjetoPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetoPagamento($objetoPagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetoPagamento', [$objetoPagamento]);

        return parent::setObjetoPagamento($objetoPagamento);
    }

}
