<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \App\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'sobrenome', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'apelido', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'rg', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cpf', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cnh', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'telefoneResidencial', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'telefoneCelular', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'endereco', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'complemento', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'bairro', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cep', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cidade', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosProfissionais', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosMedicos', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosVeiculo', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'usuarioEventos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'sobrenome', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'apelido', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'rg', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cpf', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cnh', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'sexo', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'telefoneResidencial', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'telefoneCelular', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'endereco', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'complemento', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'bairro', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cep', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'cidade', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosProfissionais', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosMedicos', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'dadosVeiculo', '' . "\0" . 'App\\Entity\\Cliente' . "\0" . 'usuarioEventos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome(string $nome): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getApelido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApelido', []);

        return parent::getApelido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApelido(string $apelido): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApelido', [$apelido]);

        return parent::setApelido($apelido);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', []);

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento(\DateTimeInterface $dataNascimento): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', [$dataNascimento]);

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', []);

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRg(string $rg): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', [$rg]);

        return parent::setRg($rg);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf(string $cpf): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnh(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnh', []);

        return parent::getCnh();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnh(string $cnh): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnh', [$cnh]);

        return parent::setCnh($cnh);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo(string $sexo): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneResidencial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneResidencial', []);

        return parent::getTelefoneResidencial();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneResidencial(string $telefoneResidencial): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneResidencial', [$telefoneResidencial]);

        return parent::setTelefoneResidencial($telefoneResidencial);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneCelular(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneCelular', []);

        return parent::getTelefoneCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneCelular(string $telefoneCelular): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneCelular', [$telefoneCelular]);

        return parent::setTelefoneCelular($telefoneCelular);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', []);

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco(string $endereco): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', [$endereco]);

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(string $numero): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', []);

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento(?string $complemento): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', [$complemento]);

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro(string $bairro): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep(string $cep): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade(string $cidade): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(string $estado): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getDadosMedicos(): ?\App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDadosMedicos', []);

        return parent::getDadosMedicos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDadosMedicos(?\App\Entity\DadosMedicos $dadosMedicos): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDadosMedicos', [$dadosMedicos]);

        return parent::setDadosMedicos($dadosMedicos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDadosVeiculo(): ?\App\Entity\DadosVeiculo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDadosVeiculo', []);

        return parent::getDadosVeiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDadosVeiculo(\App\Entity\DadosVeiculo $dadosVeiculo): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDadosVeiculo', [$dadosVeiculo]);

        return parent::setDadosVeiculo($dadosVeiculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDadosProfissionais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDadosProfissionais', []);

        return parent::getDadosProfissionais();
    }

    /**
     * {@inheritDoc}
     */
    public function setDadosProfissionais($dadosProfissionais): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDadosProfissionais', [$dadosProfissionais]);

        parent::setDadosProfissionais($dadosProfissionais);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioEventos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioEventos', []);

        return parent::getUsuarioEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuarioEvento(\App\Entity\UsuarioEvento $usuarioEvento): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuarioEvento', [$usuarioEvento]);

        return parent::addUsuarioEvento($usuarioEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuarioEvento(\App\Entity\UsuarioEvento $usuarioEvento): \App\Entity\Cliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuarioEvento', [$usuarioEvento]);

        return parent::removeUsuarioEvento($usuarioEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getSobrenome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSobrenome', []);

        return parent::getSobrenome();
    }

    /**
     * {@inheritDoc}
     */
    public function setSobrenome($sobrenome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSobrenome', [$sobrenome]);

        return parent::setSobrenome($sobrenome);
    }

}
