<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \App\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'data', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'imagem', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'localPartida', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'localChegada', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descricaoLonga', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descricaoCurta', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'valor', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'vagas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'usuarioEventos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'data', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'imagem', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'localPartida', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'localChegada', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descricaoLonga', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descricaoCurta', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'valor', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'vagas', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'usuarioEventos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVagas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVagas', []);

        return parent::getVagas();
    }

    /**
     * {@inheritDoc}
     */
    public function setVagas(string $vagas): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVagas', [$vagas]);

        return parent::setVagas($vagas);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagem(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagem', []);

        return parent::getImagem();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagem(string $imagem): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagem', [$imagem]);

        return parent::setImagem($imagem);
    }

    /**
     * {@inheritDoc}
     */
    public function getData(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData(\DateTimeInterface $data): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalPartida(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalPartida', []);

        return parent::getLocalPartida();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalPartida(string $localPartida): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalPartida', [$localPartida]);

        return parent::setLocalPartida($localPartida);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalChegada(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalChegada', []);

        return parent::getLocalChegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalChegada(string $localChegada): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalChegada', [$localChegada]);

        return parent::setLocalChegada($localChegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais(string $pais): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricaoLonga(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricaoLonga', []);

        return parent::getDescricaoLonga();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricaoLonga(string $descricaoLonga): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricaoLonga', [$descricaoLonga]);

        return parent::setDescricaoLonga($descricaoLonga);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricaoCurta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricaoCurta', []);

        return parent::getDescricaoCurta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricaoCurta(string $descricaoCurta): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricaoCurta', [$descricaoCurta]);

        return parent::setDescricaoCurta($descricaoCurta);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', []);

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor(float $valor): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', [$valor]);

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioEventos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioEventos', []);

        return parent::getUsuarioEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuarioEvento(\App\Entity\UsuarioEvento $usuarioEvento): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuarioEvento', [$usuarioEvento]);

        return parent::addUsuarioEvento($usuarioEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuarioEvento(\App\Entity\UsuarioEvento $usuarioEvento): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuarioEvento', [$usuarioEvento]);

        return parent::removeUsuarioEvento($usuarioEvento);
    }

}
