<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DadosMedicos extends \App\Entity\DadosMedicos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'tipoSanguineo', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'possuiAlergia', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'possuiDoenca', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'tomaMedicamento', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'nomePlanoSaude', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'telefonePlanoSaude', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'contatos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'tipoSanguineo', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'possuiAlergia', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'possuiDoenca', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'tomaMedicamento', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'nomePlanoSaude', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'telefonePlanoSaude', '' . "\0" . 'App\\Entity\\DadosMedicos' . "\0" . 'contatos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DadosMedicos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoSanguineo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoSanguineo', []);

        return parent::getTipoSanguineo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoSanguineo(string $tipoSanguineo): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoSanguineo', [$tipoSanguineo]);

        return parent::setTipoSanguineo($tipoSanguineo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPossuiAlergia(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPossuiAlergia', []);

        return parent::getPossuiAlergia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPossuiAlergia(bool $possuiAlergia): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPossuiAlergia', [$possuiAlergia]);

        return parent::setPossuiAlergia($possuiAlergia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPossuiDoenca(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPossuiDoenca', []);

        return parent::getPossuiDoenca();
    }

    /**
     * {@inheritDoc}
     */
    public function setPossuiDoenca(bool $possuiDoenca): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPossuiDoenca', [$possuiDoenca]);

        return parent::setPossuiDoenca($possuiDoenca);
    }

    /**
     * {@inheritDoc}
     */
    public function getTomaMedicamento(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTomaMedicamento', []);

        return parent::getTomaMedicamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTomaMedicamento(bool $tomaMedicamento): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTomaMedicamento', [$tomaMedicamento]);

        return parent::setTomaMedicamento($tomaMedicamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePlanoSaude(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePlanoSaude', []);

        return parent::getNomePlanoSaude();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePlanoSaude(string $nomePlanoSaude): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePlanoSaude', [$nomePlanoSaude]);

        return parent::setNomePlanoSaude($nomePlanoSaude);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonePlanoSaude(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonePlanoSaude', []);

        return parent::getTelefonePlanoSaude();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonePlanoSaude(?string $telefonePlanoSaude): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonePlanoSaude', [$telefonePlanoSaude]);

        return parent::setTelefonePlanoSaude($telefonePlanoSaude);
    }

    /**
     * {@inheritDoc}
     */
    public function getContatos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContatos', []);

        return parent::getContatos();
    }

    /**
     * {@inheritDoc}
     */
    public function addContato(\App\Entity\Contato $contato): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContato', [$contato]);

        return parent::addContato($contato);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContato(\App\Entity\Contato $contato): \App\Entity\DadosMedicos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContato', [$contato]);

        return parent::removeContato($contato);
    }

}
